apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myprofile-ingress
  annotations:
    # 별도의 rewrite 필요 없음
spec:
  ingressClassName: nginx
  rules:
  - host: myprofile.com
    http:
      paths:
      # 프론트
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-front-svc
            port:
              number: 80

      # 유저 API
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user-api-svc
            port:
              number: 8080

      # 프로필 API
      - path: /api/profile
        pathType: Prefix
        backend:
          service:
            name: profile-api-svc
            port:
              number: 8081

